# Generated by Django 5.1.6 on 2025-03-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='floorplans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Office')], default='living_room', max_length=50)),
                ('area_sqft', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.CharField(max_length=100)),
                ('budget_level', models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid Range'), ('luxury', 'Luxury')], max_length=20)),
                ('lighting_preference', models.CharField(choices=[('bright', 'Bright'), ('moderate', 'Moderate'), ('dim', 'Dim')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.designstyle')),
                ('floor_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.floorplan')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.ImageField(upload_to='designs/')),
                ('edge_map', models.ImageField(null=True, upload_to='edge_maps/')),
                ('prompt_used', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floorplan')),
                ('preferences', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.designpreference')),
            ],
        ),
    ]
