# Generated by Django 5.1.6 on 2025-03-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan', models.ImageField(upload_to='uploads/floor_plans/')),
                ('style_preference', models.CharField(choices=[('modern', 'Modern'), ('minimalist', 'Minimalist'), ('traditional', 'Traditional'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian')], max_length=50)),
                ('color_scheme', models.JSONField(default=dict)),
                ('generated_design', models.ImageField(blank=True, null=True, upload_to='generated/designs/')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
