# Generated by Django 5.1.6 on 2025-03-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_designrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='floorplan',
            name='area_sqft',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='room_type',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Office')], default='living_room', max_length=50),
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='edge_map',
            field=models.ImageField(null=True, upload_to='edge_maps/'),
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='processing_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='prompt_used',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.CreateModel(
            name='DesignPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.CharField(max_length=100)),
                ('budget_level', models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid Range'), ('luxury', 'Luxury')], max_length=20)),
                ('lighting_preference', models.CharField(choices=[('bright', 'Bright'), ('moderate', 'Moderate'), ('dim', 'Dim')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('floor_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.floorplan')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.designstyle')),
            ],
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.designpreference'),
        ),
        migrations.DeleteModel(
            name='DesignRequest',
        ),
    ]
