# Generated by Django 5.1.6 on 2025-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpreference',
            name='budget_level',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='color_scheme',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='lighting_preference',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='style',
        ),
        migrations.AddField(
            model_name='designpreference',
            name='color_palette',
            field=models.CharField(choices=[('neutral', 'Neutral & Earthy'), ('warm', 'Warm & Cozy'), ('cool', 'Cool & Calm'), ('vibrant', 'Vibrant & Bold'), ('monochrome', 'Monochromatic'), ('pastel', 'Soft Pastels')], default='neutral', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='inspiration_image',
            field=models.ImageField(blank=True, null=True, upload_to='inspirations/'),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='lighting_type',
            field=models.CharField(choices=[('natural', 'Natural Lighting'), ('ambient', 'Ambient Lighting'), ('task', 'Task Lighting'), ('accent', 'Accent Lighting'), ('mixed', 'Mixed Lighting')], default='natural', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='material_preference',
            field=models.CharField(choices=[('wood', 'Natural Wood'), ('metal', 'Metal & Industrial'), ('fabric', 'Soft Fabrics'), ('glass', 'Glass & Mirrors'), ('stone', 'Stone & Marble'), ('mixed', 'Mixed Materials')], default='wood', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='space_layout',
            field=models.CharField(choices=[('open', 'Open & Spacious'), ('cozy', 'Cozy & Intimate'), ('minimalist', 'Clean & Minimal'), ('functional', 'Functional & Practical'), ('flexible', 'Flexible & Adaptable')], default='open', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='style_preference',
            field=models.CharField(choices=[('modern', 'Modern'), ('contemporary', 'Contemporary'), ('traditional', 'Traditional'), ('minimalist', 'Minimalist'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian')], default='modern', max_length=100),
        ),
    ]
