# Generated by Django 5.1.6 on 2025-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_designpreference_budget_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpreference',
            name='color_palette',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='inspiration_image',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='lighting_type',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='material_preference',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='space_layout',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='style_preference',
        ),
        migrations.AddField(
            model_name='designpreference',
            name='accessories',
            field=models.CharField(default='Minimalist decor, plants', max_length=200),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='color',
            field=models.CharField(default='Neutral', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='furniture',
            field=models.CharField(default='Modern sofa, coffee table', max_length=200),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='lights',
            field=models.CharField(default='Recessed lighting', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='realistic',
            field=models.CharField(default='Photorealistic', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='theme',
            field=models.CharField(default='Modern', max_length=100),
        ),
        migrations.AddField(
            model_name='designpreference',
            name='walls',
            field=models.CharField(default='White textured', max_length=100),
        ),
    ]
