# Generated by Django 5.1.6 on 2025-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_designstyle_floorplan_area_sqft_floorplan_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpreference',
            name='color_scheme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
