# Generated by Django 5.1.6 on 2025-03-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_designpreference_color_palette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpreference',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='lights',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='realistic',
        ),
        migrations.RemoveField(
            model_name='designpreference',
            name='walls',
        ),
    ]
