# Generated by Django 5.1.6 on 2025-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_designpreference_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpreference',
            name='color_scheme',
            field=models.CharField(max_length=100),
        ),
    ]
