services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      AWS_BUCKET_NAME: "your_bucket_name"
      AWS_REGION: "your_aws_region"
      AWS_ACCESS_KEY_ID: "your_access_key"
      AWS_SECRET_ACCESS_KEY: "your_secret_access_key"
      REPLICATE_API_TOKEN: "your_replicate_api_token"
      DJANGO_SECRET_KEY: "your_django_secret_key"
      DEBUG: 'True'
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgres://usmanmufti:1234567890@db:5432/interior_pilot


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    command: npm run dev -- --host
